version: "3.3"

services:
    apache:
        build:
          context: apache
        ports:
            - "8080:80"
        volumes:
            - "../:/var/www/html/:delegated"

    php:
        build:
          context: php7.4
        env_file: ../.env
        volumes:
            - "../:/var/www/:delegated"
    db:
        command: --default-authentication-plugin=mysql_native_password
        build:
            context: mysql
        ports:
            - "3306:3306"
        restart: always
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_ROOT_PASSWORD=root
