website:
    path:     /
    defaults: { _controller: "websitesManagementBundle:Website:index" }
website_show:
    path:     /{id}/show
    defaults: { _controller: websitesManagementBundle:Website:show }

website_new:
    path:     /new
    defaults: { _controller: websitesManagementBundle:Website:new }

website_create:
    path:     /create
    defaults: { _controller: "websitesManagementBundle:Website:create" }
    methods:  POST

website_edit:
    path:     /{id}/edit
    defaults: { _controller: "websitesManagementBundle:Website:edit" }

website_update:
    path:     /{id}/update
    defaults: { _controller: "websitesManagementBundle:Website:update" }
    methods:  [POST, PUT]

website_delete:
    path:     /{id}/delete
    defaults: { _controller: "websitesManagementBundle:Website:delete" }
    methods:  [GET]